use QLSVNhom
GO
CREATE OR ALTER PROCEDURE SP_INS_SINHVIEN
    @masv NVARCHAR(20),
    @hoten NVARCHAR(100),
    @ngaysinh DATETIME,
    @diachi NVARCHAR(200),
    @malop VARCHAR(20),
    @tendn NVARCHAR(100),
    @matkhau NVARCHAR(100)
AS
INSERT INTO SINHVIEN VALUES (@masv, @hoten, @ngaysinh, @diachi, @malop, @tendn, HASHBYTES('MD5', @matkhau))
GO
EXEC SP_INS_SINHVIEN 'SV01', 'NGUYEN VAN A', '1/1/1990', '281 AN DUONG VUONG', 'NVA', 'dn1', '123456'
EXEC SP_INS_SINHVIEN 'SV03', 'NGUYEN VAN C', '3/3/1990', '283 AN DUONG VUONG', 'NVA', 'dn3', '123456'
EXEC SP_INS_SINHVIEN 'SV02', 'NGUYEN VAN B', '2/2/1990', '282 AN DUONG VUONG', 'NVB', 'dn2', '123456'

EXEC SP_INS_PUBLIC_NHANVIEN 'NV01', 'NGUYEN VAN A', 'nva@yahoo.com',3000000, 'NVA', '123456'
EXEC SP_INS_PUBLIC_NHANVIEN 'NV02', 'NGUYEN VAN B', 'nvb@yahoo.com',2000000, 'NVB', '1234567'

EXEC SP_SEL_PUBLIC_NHANVIEN 'NVA', '123456'
EXEC SP_SEL_PUBLIC_NHANVIEN 'NVB', '1234567'

INSERT INTO LOP VALUES('NVA',N'Lớp A','NV01')
INSERT INTO LOP VALUES('NVB',N'Lớp B','NV02')

INSERT INTO HOCPHAN VALUES('BMCSDL',N'Bảo mật cơ sở dữ liệu',4)
INSERT INTO HOCPHAN VALUES('NMHM',N'Nhập môn học máy',4)

INSERT INTO BANGDIEM VALUES('SV01','BMCSDL',NULL)
INSERT INTO BANGDIEM VALUES('SV01','NMHM',NULL)
INSERT INTO BANGDIEM VALUES('SV02','BMCSDL',NULL)
INSERT INTO BANGDIEM VALUES('SV01','NMHM',NULL)
INSERT INTO BANGDIEM VALUES('SV03','BMCSDL',NULL)
INSERT INTO BANGDIEM VALUES('SV01','NMHM',NULL)

