/*----------------------------------------------------------
MASV: 19120083 - 19120120 - 19120455
HO TEN: Nguyen Trong Kha - Pham Huu Phuoc - Huynh Ngoc Bao
LAB: 03 - NHOM
NGAY: 26/4/2022
----------------------------------------------------------*/

use QLSVNhom
GO

-- Create the table NHANVIEN
CREATE TABLE NHANVIEN
(
    MANV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(20),
    LUONG VARBINARY(1000),
    TENDN NVARCHAR(100) NOT NULL,
    MATKHAU VARBINARY(20) NOT NULL,
	PUBKEY VARCHAR(20) NOT NULL,
);

-- Create the table LOP
CREATE TABLE LOP
(
    MALOP VARCHAR(20) PRIMARY KEY,
    TENLOP NVARCHAR(100) NOT NULL,
    MANV VARCHAR(20),
);

-- Create the table SINHVIEN
CREATE TABLE SINHVIEN
(
    MASV NVARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATETIME,
    DIACHI NVARCHAR(200),
    MALOP VARCHAR(20),
    TENDN NVARCHAR(100) NOT NULL,
    MATKHAU VARBINARY(16) NOT NULL,
);

-- Create the table HOCPHAN
CREATE TABLE HOCPHAN
(
    MAHP VARCHAR(20) PRIMARY KEY,
    TENHP NVARCHAR(100) NOT NULL,
    SOTC INT,
);

-- Create the table BANGDIEM
CREATE TABLE BANGDIEM
(
    MASV VARCHAR(20),
    MAHP VARCHAR(100),
    DIEMTHI VARBINARY(1000),
	CONSTRAINT PK_BANGDIEM PRIMARY KEY (MASV,MAHP)
);